### ISSUE TITLE
Link al manuale ver. 0.97 rotto

### ISSUE THREAD

**Issue by mfvescovi** [scapretta/Sinx#1]
Il [link](http://www.sinx.it/Download/Manuale_097.pdf) riportato nel sito ed anche quello nel README.md puntano ad un file non più esistente.

**Comment by alfredo978** [comment]
Carica la copia cache di quella pagina e puff..esce il manuale, ma a me non funziona comunque :)

**Comment by scapretta** [comment]
[Manuale](http://www.mokazine.com/read/sinx/manuale-di-sinx-versione-0-97)

**Comment by mfvescovi** [comment]
Ma il mio issue era stato aperto per richiedere che venisse risolto il problema del '404' sul sito. Va beh.
A questo punto posso pure chiederlo, tanto non ci siamo comunque capiti.
