### ISSUE TITLE
Installato e non funzionante

### ISSUE THREAD

**Issue by DareDevil73** [scapretta/Sinx#11]
Buonasera, ho installato il software ad uso della mia associazione di protezione civile.

Dopo aver eseguito l'installazione, al primo login ottengo quanto visibile in allegato.
![sinx - chromium_003](https://user-images.githubusercontent.com/6660386/36632293-5481e886-1985-11e8-822a-0f40261fa3d1.jpg). 

Nel log degli errori sono presenti le seguenti informazioni:

> [Sat Feb 24 16:58:29.994213 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 75
[Sat Feb 24 16:58:30.305152 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 87
[Sat Feb 24 16:58:30.624659 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 117
[Sat Feb 24 16:58:30.945105 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 128
[Sat Feb 24 16:58:31.239356 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 147
[Sat Feb 24 16:58:31.550498 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 161
[Sat Feb 24 16:58:31.862743 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 175
[Sat Feb 24 16:58:32.123717 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 188
[Sat Feb 24 16:58:32.384627 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 201
[Sat Feb 24 16:58:32.720792 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 220
[Sat Feb 24 16:58:32.991297 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 234
[Sat Feb 24 16:58:33.302280 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 247
[Sat Feb 24 16:58:33.353270 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 261
[Sat Feb 24 16:58:33.706924 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 274
[Sat Feb 24 16:58:33.757963 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 288
[Sat Feb 24 16:58:33.808728 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 300
[Sat Feb 24 16:58:33.859342 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 313
[Sat Feb 24 16:58:34.169936 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 331
[Sat Feb 24 16:58:34.480864 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  mysqli::query() expects parameter 1 to be string, object given in /var/www/Sinx/Install/index.php on line 345
[Sat Feb 24 16:58:48.863638 2018] [:error] [pid 2226] [client 192.168.1.3:50334] PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/Sinx/Install/index.php:8834) in /var/www/Sinx/Install/index.php on line 8869
sh: 1: /usr/sbin/sendmail: not found
[Sat Feb 24 17:02:37.461673 2018] [:error] [pid 2233] [client 192.168.1.3:50416] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/Sinx/menu.inc on line 2, referer: http://192.168.1.6/index.php
[Sat Feb 24 17:02:37.470404 2018] [:error] [pid 2233] [client 192.168.1.3:50416] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/Sinx/menusx.inc on line 35, referer: http://192.168.1.6/index.php
[Sat Feb 24 17:02:37.473235 2018] [:error] [pid 2233] [client 192.168.1.3:50416] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/Sinx/Mese.php on line 19, referer: http://192.168.1.6/index.php
[Sat Feb 24 17:02:43.748778 2018] [:error] [pid 2232] [client 192.168.1.3:50422] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/Sinx/menu.inc on line 2, referer: http://192.168.1.6/index.php
[Sat Feb 24 17:02:43.754825 2018] [:error] [pid 2232] [client 192.168.1.3:50422] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/Sinx/menusx.inc on line 35, referer: http://192.168.1.6/index.php
[Sat Feb 24 17:02:43.755943 2018] [:error] [pid 2232] [client 192.168.1.3:50422] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/Sinx/Mese.php on line 19, referer: http://192.168.1.6/index.php
[Sat Feb 24 17:03:17.421760 2018] [:error] [pid 2229] [client 192.168.1.3:50434] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/Sinx/menu.inc on line 2, referer: http://192.168.1.6/index.php
[Sat Feb 24 17:03:17.427515 2018] [:error] [pid 2229] [client 192.168.1.3:50434] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/Sinx/menusx.inc on line 35, referer: http://192.168.1.6/index.php
[Sat Feb 24 17:03:17.428991 2018] [:error] [pid 2229] [client 192.168.1.3:50434] PHP Notice:  A session had already been started - ignoring session_start() in /var/www/Sinx/Mese.php on line 19, referer: http://192.168.1.6/index.php

Il sw è installato su Ubuntu 16.04 server, Apache 2, Php 7, MySQL 5.2.

Potete cortesemente indicarmi come risolvere il problema? Pensate sia opportuno l'installazione di PHP 5 al posto del 7?

Molte grazie,
Antonio Petricca

**Edit** Anche con PHP 5.6 ottengo esattamente lo stesso errore.

**Comment by elmer120** [comment]
Buonasera!
Potrebbe spostare la discussione sul forum - nella sezione Installazione di Sinx? grazie.
[forum](sinx.forumattivo.com)

**Comment by DareDevil73** [comment]
Ho provato a farlo, mi sono iscritto, ma non posso postare immagini o link per i primi 7 giorni.

Potrebbe aiutarmi comunque?

Molte grazie!!!
Antonio
