### ISSUE TITLE
fattura con riga iva

### ISSUE THREAD

**Issue by dikdust** [scapretta/Sinx#12]
Ciao a tutti ho fatto una piccola modifica a stampa_fattura.php poichè il commercialista mi chiedeva la riga iva separata. Non sono uno sviluppatore per cui sicuramente si poteva fare meglio ma comunque qua sotto i miei due cents ....

[stampa_fattura_php.txt](https://github.com/scapretta/Sinx/files/1777125/stampa_fattura_php.txt)

**Comment by scapretta** [comment]
Ogni più piccolo contributo, va benissimo. Grazie
