### ISSUE TITLE
README.md riporta una versione errata del codice

### ISSUE THREAD

**Issue by mfvescovi** [scapretta/Sinx#2]
"Sinx for Association V 0.93.4" quando quella rilasciata è la 0.98.9.

**Comment by mfvescovi** [comment]
Tempo perso.

**Comment by elmer120** [comment]
grazie della segnalazione, la prendo in carico io ;)
Se hai altre segnalazioni sono ben accette.
Puoi farle qui o sul forum ;) [Link al forum](http://sinx.forumattivo.com/login)

**Comment by mfvescovi** [comment]
Il forum richiede registrazione. Preferisco contribuire da qui, nel caso.
