### ISSUE TITLE
Problema SQL syntax

### ISSUE THREAD

**Issue by Andrea996** [scapretta/Sinx#4]
Buongiorno, quando faccio per installare il CMS mi esce questo messaggio:
Mi connetto al database...Connessione riuscita.

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ODV o APS VARCHAR(200) DEFAULT NULL, PRIMARY KEY (id_anagrafe))' at line 26

Mi fa procedere con l'installazione ma poi all'accesso non funziona ed esce il seguente messaggio: Errore: Impossibile eseguire la query della Combo

Come posso risolvere ? Grazie

**Comment by ingesiit** [comment]
Ho lo stesso problema anch'io, avete suggerimenti?

Grazie in anticipo

Alessandro Barisone

**Comment by laspapier** [comment]
Anch'io ho lo stesso errore...correggo il primo errore di sintassi Sql e installo tutto, ma dopo che faccio il login mi compare 
Errore: Impossibile eseguire la query della Combo
cosa fare?
Grazie

**Comment by laspapier** [comment]
Ho risolto...praticamente nel file index.php della cartella install si deve eliminare la riga 61 che è un doppione della riga 58 "webmail" e così funziona tutto

**Comment by scapretta** [comment]
Ho corretto il file. il problema erano gli spazi, adesso dovrebbe essere corretto. Grazie per la segnalazione

**Comment by ingesiit** [comment]
Il primo errore (quello alla riga IscrizioneODVoAPS che prima aveva degli spazi di troppo) è risolto
C'è ancora un secondo errore, come segnalato sopra da Laspapier ("webmail" dichiarata due volte nella query, che fa fallire la query). Modificando a mano si è installato

Saluti

Alessandro Barisone

**Comment by scapretta** [comment]
Grazie, sistemato anche quell'errore
