### ISSUE TITLE
Inserimento soci

### ISSUE THREAD

**Issue by thestrangehat77** [scapretta/Sinx#5]
InsAnagrIns.php alla riga 68  
$rs=mysqli_query($query) or die("<b>Errore:</b> Impossibile eseguire la query della Combo");

produce un errore senza output; il rendering della pagina termina senza disegnare il pulsante "invia"

Ho verificato che risolve con 
 
$rs=mysqli_query($connect,  $query) or die("<b>Errore:</b> Impossibile eseguire la query della Combo");

**Comment by scapretta** [comment]
corretto, grazie

**Comment by laspapier** [comment]
Scusate..ho riscontrato un altro errore. Una volta installato il tutto se vado a modificare i dati sulla schermata "Dati dell'Associazione" viene vuori la scritto "I dati non sono corretti" e non si aggiorna. Come mai?

**Comment by scapretta** [comment]
Ciao, questo succede quando inserisci caratteri "strani" come l'apostrofo o simili; è una protezione per evitare che qualche malintenzionato non vada a scrivere codice all'interno delle caselle di testo

**Comment by laspapier** [comment]
Ma così non posso inserire il link del sito né di facebook visti che inevitabilmente ci sono gli /..

**Comment by scapretta** [comment]
I link ed i relativi simboli si possono inserire, solo alcuni caratteri sono bloccati

**Comment by laspapier** [comment]
La cosa strana è che inserendo gli stessi dati dall'app android non mi da nessun problema..invece con il pc si!
