### ISSUE TITLE
Pagina per modificare associati

### ISSUE THREAD

**Issue by Andrea996** [scapretta/Sinx#8]
Buonasera, non riesco a trovare la pagina per modificare i dati dei soci già inseriti 
Esiste ? O devo fare da DB 

Grazie

**Comment by elmer120** [comment]
Menu --> Anagrafica --> Cerca --> trova "associati".
Clicca su nome ---> compariranno tutti gli associati.
Clicca sul pulsante con numero dell'id.
Si apre la scheda associato. Vicino a "modifica" c'è il pulsante con numero dell'id.
A quel punto trovi la sezione dove è possibile modificare l'associato.
