### ISSUE TITLE
installazione su Xampp

### ISSUE THREAD

**Issue by claudiopapa** [scapretta/Sinx#9]
salve,
installando l'applicativo su xampp (ultima release) riscontro diversi warning ed errori.

in fase di instalalzione:
Warning: mysqli::query() expects parameter 1 to be string

dopo installazione sulla schermata iniziale:
Notice: session_start(): A session had already been started 

ed altri errori nelle pagine successive (tipo Associati)
Notice: Undefined variable: limit in D:\xampp\htdocs\AP\InsAnagrIns.php on line 83

da cosa potrebbe dipendere ?

saluti
Claudio

**Comment by elmer120** [comment]
Potresti spostare la discussione sul forum? grazie
[http://sinx.forumattivo.com/](url)

**Comment by claudiopapa** [comment]
fatto

**Comment by elmer120** [comment]
link discussione: [http://sinx.forumattivo.com/t6-bug-installazione-xammp#23](url)
